name: Build

on:
  push:
    branches: 
      - "**"
    tags:
      - "*"

permissions: 
  checks: write
  pull-requests: write

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  validate-version:
    name: 🧐 Validate Version
    uses: ./.github/workflows/validate-version-job.yml
    if: startsWith(github.ref, 'refs/tags/')

  build:
    name: 🏗️ Build Nuget Package
    uses: ./.github/workflows/build-job.yml
    with:
      dotnet-version: "${{ env.DOTNET_VERSION }}"
      use-local-projects: false
      create-nuget-package: true

  build-against-sources:
    name: 🏗️ Build Against Sources
    uses: ./.github/workflows/build-job.yml
    with:
      dotnet-version: "${{ env.DOTNET_VERSION }}"
      use-local-projects: true
      create-nuget-package: false

  test:
    name: ✅ Run Tests
    uses: ./.github/workflows/test-job.yml
    needs: [build, build-against-sources]
    with:
      dotnet-version: "${{ env.DOTNET_VERSION }}"
  
  publish-nuget:
    name: 📦 Publish Nuget Package
    uses: ./.github/workflows/publish-nuget-job.yml
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    with:
      dotnet-version: "${{ env.DOTNET_VERSION }}"
    secrets: inherit
