on:
  workflow_call:
    inputs: 
      dotnet-version:
        required: false 
        type: string

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.discover.outputs.matrix }}
    steps:
      - name: 🗃️ Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: 🔎 Find all .NET test projects
        id: discover
        run: |
          projects=$(find . -name "*Tests.csproj" -o -name "*.Test.csproj" -o -name "*.Tests.csproj")
          arr=()
          for project in $projects; do
            filename=$(basename "$project")
            name="${filename%.csproj}"   # remove .csproj
            working-directory=$(dirname "$project") 
            items+=("{\"name\":\"$name\",\"path\":\"$project\",\"working-directory\":\"$working-directory\"}")
          done

          json="[$(IFS=,; echo "${items[*]}")]"
          
          echo "Found test projects: $json"
          echo "matrix={\"project\":$json}" >> $GITHUB_OUTPUT

  run:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}

    name: ${{ matrix.project.name }}

    steps:
      - name: 🗃️ Checkout
        uses: actions/checkout@v4

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: 🔄 Restore
        run: dotnet restore "${{ matrix.project.path }}"

      - name: 🏃‍♂️‍➡️ Run Test
        run: 
          |
            dotnet run "${{ matrix.project.path }}" 
              --configuration Release 
              --no-restore 
              --report-trx 
              --report-trx-filename ${{ matrix.project.name }}-results.trx
              --results-directory "${{ matrix.project.working-directory }}"

      - name: 📤 Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project.name }}-results.trx
          path: "${{ matrix.project.working-directory }}"
